### ISSUE TITLE
/epsearch/view.py: UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-18: ordinal not in range(128)

### ISSUE THREAD

**Issue by kwbt69** [r-stack/edupedia#4]
ERROR 2016-05-30 09:14:48,492 base 15571 139912748468224 Internal Server Error: /search/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, _args, *_kwargs)
  File "./epsearch/views.py", line 20, in get
    force=request.GET.get("f"))
  File "./epsearch/views.py", line 35, in load_page
    print u"[S] load_page: %s" % pagename
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-18: ordinal not in range(128)

**Comment by kiikura** [comment]
ローカルだと出てなかったような気がするのでurlencode周りかな

**Comment by kiikura** [comment]
標準出力のpython出力だきっと

環境変数設定するか loggingに変えよう

**Comment by kiikura** [comment]
```
SET PYTHONIOENCODING=ascii
```

にしたらローカルでも再現できました。というわけでloggingに変えます。
